wandb_version: 1

epochs:
  desc: null
  value: 199
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709366894.05702
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 71
      - 83
      2:
      - 1
      - 41
      - 49
      - 55
      - 71
      - 83
      3:
      - 13
      - 16
      4: 3.9.18
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
